/**
 * This file is part of the OGEMA widgets framework.
 *
 * OGEMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * OGEMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OGEMA. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright 2014 - 2018
 *
 * Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Fraunhofer IWES/Fraunhofer IEE
 */

package de.iwes.widgets.html;

/**
 * Bootstrap glyphicon identifiers:
 * http://getbootstrap.com/components/#glyphicons 
 */
public class Glyphicons {

    public static final String ASTERISK = "glyphicon glyphicon-asterisk";
    public static final String PLUS = "glyphicon glyphicon-plus";
    public static final String EURO = "glyphicon glyphicon-euro";
    public static final String EUR = "glyphicon glyphicon-eur";
    public static final String MINUS = "glyphicon glyphicon-minus";
    public static final String CLOUD = "glyphicon glyphicon-cloud";
    public static final String ENVELOPE = "glyphicon glyphicon-envelope";
    public static final String PENCIL = "glyphicon glyphicon-pencil";
    public static final String GLASS = "glyphicon glyphicon-glass";
    public static final String MUSIC = "glyphicon glyphicon-music";
    public static final String SEARCH = "glyphicon glyphicon-search";
    public static final String HEART = "glyphicon glyphicon-heart";
    public static final String STAR = "glyphicon glyphicon-star";
    public static final String STAR_EMPTY = "glyphicon glyphicon-star-empty";
    public static final String USER = "glyphicon glyphicon-user";
    public static final String FILM = "glyphicon glyphicon-film";
    public static final String TH_LARGE = "glyphicon glyphicon-th-large";
    public static final String TH = "glyphicon glyphicon-th";
    public static final String TH_LIST = "glyphicon glyphicon-th-list";
    public static final String OK = "glyphicon glyphicon-ok";
    public static final String REMOVE = "glyphicon glyphicon-remove";
    public static final String ZOOM_IN = "glyphicon glyphicon-zoom-in";
    public static final String ZOOM_OUT = "glyphicon glyphicon-zoom-out";
    public static final String OFF = "glyphicon glyphicon-off";
    public static final String SIGNAL = "glyphicon glyphicon-signal";
    public static final String COG = "glyphicon glyphicon-cog";
    public static final String TRASH = "glyphicon glyphicon-trash";
    public static final String HOME = "glyphicon glyphicon-home";
    public static final String FILE = "glyphicon glyphicon-file";
    public static final String TIME = "glyphicon glyphicon-time";
    public static final String ROAD = "glyphicon glyphicon-road";
    public static final String DOWNLOAD_ALT = "glyphicon glyphicon-download-alt";
    public static final String DOWNLOAD = "glyphicon glyphicon-download";
    public static final String UPLOAD = "glyphicon glyphicon-upload";
    public static final String INBOX = "glyphicon glyphicon-inbox";
    public static final String PLAY_CIRCLE = "glyphicon glyphicon-play-circle";
    public static final String REPEAT = "glyphicon glyphicon-repeat";
    public static final String REFRESH = "glyphicon glyphicon-refresh";
    public static final String LIST_ALT = "glyphicon glyphicon-list-alt";
    public static final String LOCK = "glyphicon glyphicon-lock";
    public static final String FLAG = "glyphicon glyphicon-flag";
    public static final String HEADPHONES = "glyphicon glyphicon-headphones";
    public static final String VOLUME_OFF = "glyphicon glyphicon-volume-off";
    public static final String VOLUME_DOWN = "glyphicon glyphicon-volume-down";
    public static final String VOLUME_UP = "glyphicon glyphicon-volume-up";
    public static final String QRCODE = "glyphicon glyphicon-qrcode";
    public static final String BARCODE = "glyphicon glyphicon-barcode";
    public static final String TAG = "glyphicon glyphicon-tag";
    public static final String TAGS = "glyphicon glyphicon-tags";
    public static final String BOOK = "glyphicon glyphicon-book";
    public static final String BOOKMARK = "glyphicon glyphicon-bookmark";
    public static final String PRINT = "glyphicon glyphicon-print";
    public static final String CAMERA = "glyphicon glyphicon-camera";
    public static final String FONT = "glyphicon glyphicon-font";
    public static final String BOLD = "glyphicon glyphicon-bold";
    public static final String ITALIC = "glyphicon glyphicon-italic";
    public static final String TEXT_HEIGHT = "glyphicon glyphicon-text-height";
    public static final String TEXT_WIDTH = "glyphicon glyphicon-text-width";
    public static final String ALIGN_LEFT = "glyphicon glyphicon-align-left";
    public static final String ALIGN_CENTER = "glyphicon glyphicon-align-center";
    public static final String ALIGN_RIGHT = "glyphicon glyphicon-align-right";
    public static final String ALIGN_JUSTIFY = "glyphicon glyphicon-align-justify";
    public static final String LIST = "glyphicon glyphicon-list";
    public static final String INDENT_LEFT = "glyphicon glyphicon-indent-left";
    public static final String INDENT_RIGHT = "glyphicon glyphicon-indent-right";
    public static final String FACETIME_VIDEO = "glyphicon glyphicon-facetime-video";
    public static final String PICTURE = "glyphicon glyphicon-picture";
    public static final String MAP_MARKER = "glyphicon glyphicon-map-marker";
    public static final String ADJUST = "glyphicon glyphicon-adjust";
    public static final String TINT = "glyphicon glyphicon-tint";
    public static final String EDIT = "glyphicon glyphicon-edit";
    public static final String SHARE = "glyphicon glyphicon-share";
    public static final String CHECK = "glyphicon glyphicon-check";
    public static final String MOVE = "glyphicon glyphicon-move";
    public static final String STEP_BACKWARD = "glyphicon glyphicon-step-backward";
    public static final String FAST_BACKWARD = "glyphicon glyphicon-fast-backward";
    public static final String BACKWARD = "glyphicon glyphicon-backward";
    public static final String PLAY = "glyphicon glyphicon-play";
    public static final String PAUSE = "glyphicon glyphicon-pause";
    public static final String STOP = "glyphicon glyphicon-stop";
    public static final String FORWARD = "glyphicon glyphicon-forward";
    public static final String FAST_FORWARD = "glyphicon glyphicon-fast-forward";
    public static final String STEP_FORWARD = "glyphicon glyphicon-step-forward";
    public static final String EJECT = "glyphicon glyphicon-eject";
    public static final String CHEVRON_LEFT = "glyphicon glyphicon-chevron-left";
    public static final String CHEVRON_RIGHT = "glyphicon glyphicon-chevron-right";
    public static final String PLUS_SIGN = "glyphicon glyphicon-plus-sign";
    public static final String MINUS_SIGN = "glyphicon glyphicon-minus-sign";
    public static final String REMOVE_SIGN = "glyphicon glyphicon-remove-sign";
    public static final String OK_SIGN = "glyphicon glyphicon-ok-sign";
    public static final String QUESTION_SIGN = "glyphicon glyphicon-question-sign";
    public static final String INFO_SIGN = "glyphicon glyphicon-info-sign";
    public static final String SCREENSHOT = "glyphicon glyphicon-screenshot";
    public static final String REMOVE_CIRCLE = "glyphicon glyphicon-remove-circle";
    public static final String OK_CIRCLE = "glyphicon glyphicon-ok-circle";
    public static final String BAN_CIRCLE = "glyphicon glyphicon-ban-circle";
    public static final String ARROW_LEFT = "glyphicon glyphicon-arrow-left";
    public static final String ARROW_RIGHT = "glyphicon glyphicon-arrow-right";
    public static final String ARROW_UP = "glyphicon glyphicon-arrow-up";
    public static final String ARROW_DOWN = "glyphicon glyphicon-arrow-down";
    public static final String SHARE_ALT = "glyphicon glyphicon-share-alt";
    public static final String RESIZE_FULL = "glyphicon glyphicon-resize-full";
    public static final String RESIZE_SMALL = "glyphicon glyphicon-resize-small";
    public static final String EXCLAMATION_SIGN = "glyphicon glyphicon-exclamation-sign";
    public static final String GIFT = "glyphicon glyphicon-gift";
    public static final String LEAF = "glyphicon glyphicon-leaf";
    public static final String FIRE = "glyphicon glyphicon-fire";
    public static final String EYE_OPEN = "glyphicon glyphicon-eye-open";
    public static final String EYE_CLOSE = "glyphicon glyphicon-eye-close";
    public static final String WARNING_SIGN = "glyphicon glyphicon-warning-sign";
    public static final String PLANE = "glyphicon glyphicon-plane";
    public static final String CALENDAR = "glyphicon glyphicon-calendar";
    public static final String RANDOM = "glyphicon glyphicon-random";
    public static final String COMMENT = "glyphicon glyphicon-comment";
    public static final String MAGNET = "glyphicon glyphicon-magnet";
    public static final String CHEVRON_UP = "glyphicon glyphicon-chevron-up";
    public static final String CHEVRON_DOWN = "glyphicon glyphicon-chevron-down";
    public static final String RETWEET = "glyphicon glyphicon-retweet";
    public static final String SHOPPING_CART = "glyphicon glyphicon-shopping-cart";
    public static final String FOLDER_CLOSE = "glyphicon glyphicon-folder-close";
    public static final String FOLDER_OPEN = "glyphicon glyphicon-folder-open";
    public static final String RESIZE_VERTICAL = "glyphicon glyphicon-resize-vertical";
    public static final String RESIZE_HORIZONTAL = "glyphicon glyphicon-resize-horizontal";
    public static final String HDD = "glyphicon glyphicon-hdd";
    public static final String BULLHORN = "glyphicon glyphicon-bullhorn";
    public static final String BELL = "glyphicon glyphicon-bell";
    public static final String CERTIFICATE = "glyphicon glyphicon-certificate";
    public static final String THUMBS_UP = "glyphicon glyphicon-thumbs-up";
    public static final String THUMBS_DOWN = "glyphicon glyphicon-thumbs-down";
    public static final String HAND_RIGHT = "glyphicon glyphicon-hand-right";
    public static final String HAND_LEFT = "glyphicon glyphicon-hand-left";
    public static final String HAND_UP = "glyphicon glyphicon-hand-up";
    public static final String HAND_DOWN = "glyphicon glyphicon-hand-down";
    public static final String CIRCLE_ARROW_RIGHT = "glyphicon glyphicon-circle-arrow-right";
    public static final String CIRCLE_ARROW_LEFT = "glyphicon glyphicon-circle-arrow-left";
    public static final String CIRCLE_ARROW_UP = "glyphicon glyphicon-circle-arrow-up";
    public static final String CIRCLE_ARROW_DOWN = "glyphicon glyphicon-circle-arrow-down";
    public static final String GLOBE = "glyphicon glyphicon-globe";
    public static final String WRENCH = "glyphicon glyphicon-wrench";
    public static final String TASKS = "glyphicon glyphicon-tasks";
    public static final String FILTER = "glyphicon glyphicon-filter";
    public static final String BRIEFCASE = "glyphicon glyphicon-briefcase";
    public static final String FULLSCREEN = "glyphicon glyphicon-fullscreen";
    public static final String DASHBOARD = "glyphicon glyphicon-dashboard";
    public static final String PAPERCLIP = "glyphicon glyphicon-paperclip";
    public static final String HEART_EMPTY = "glyphicon glyphicon-heart-empty";
    public static final String LINK = "glyphicon glyphicon-link";
    public static final String PHONE = "glyphicon glyphicon-phone";
    public static final String PUSHPIN = "glyphicon glyphicon-pushpin";
    public static final String USD = "glyphicon glyphicon-usd";
    public static final String GBP = "glyphicon glyphicon-gbp";
    public static final String SORT = "glyphicon glyphicon-sort";
    public static final String SORT_BY_ALPHABET = "glyphicon glyphicon-sort-by-alphabet";
    public static final String SORT_BY_ALPHABET_ALT = "glyphicon glyphicon-sort-by-alphabet-alt";
    public static final String SORT_BY_ORDER = "glyphicon glyphicon-sort-by-order";
    public static final String SORT_BY_ORDER_ALT = "glyphicon glyphicon-sort-by-order-alt";
    public static final String SORT_BY_ATTRIBUTES = "glyphicon glyphicon-sort-by-attributes";
    public static final String SORT_BY_ATTRIBUTES_ALT = "glyphicon glyphicon-sort-by-attributes-alt";
    public static final String UNCHECKED = "glyphicon glyphicon-unchecked";
    public static final String EXPAND = "glyphicon glyphicon-expand";
    public static final String COLLAPSE_DOWN = "glyphicon glyphicon-collapse-down";
    public static final String COLLAPSE_UP = "glyphicon glyphicon-collapse-up";
    public static final String LOG_IN = "glyphicon glyphicon-log-in";
    public static final String FLASH = "glyphicon glyphicon-flash";
    public static final String LOG_OUT = "glyphicon glyphicon-log-out";
    public static final String NEW_WINDOW = "glyphicon glyphicon-new-window";
    public static final String RECORD = "glyphicon glyphicon-record";
    public static final String SAVE = "glyphicon glyphicon-save";
    public static final String OPEN = "glyphicon glyphicon-open";
    public static final String SAVED = "glyphicon glyphicon-saved";
    public static final String IMPORT = "glyphicon glyphicon-import";
    public static final String EXPORT = "glyphicon glyphicon-export";
    public static final String SEND = "glyphicon glyphicon-send";
    public static final String FLOPPY_DISK = "glyphicon glyphicon-floppy-disk";
    public static final String FLOPPY_SAVED = "glyphicon glyphicon-floppy-saved";
    public static final String FLOPPY_REMOVE = "glyphicon glyphicon-floppy-remove";
    public static final String FLOPPY_SAVE = "glyphicon glyphicon-floppy-save";
    public static final String FLOPPY_OPEN = "glyphicon glyphicon-floppy-open";
    public static final String CREDIT_CARD = "glyphicon glyphicon-credit-card";
    public static final String TRANSFER = "glyphicon glyphicon-transfer";
    public static final String CUTLERY = "glyphicon glyphicon-cutlery";
    public static final String HEADER = "glyphicon glyphicon-header";
    public static final String COMPRESSED = "glyphicon glyphicon-compressed";
    public static final String EARPHONE = "glyphicon glyphicon-earphone";
    public static final String PHONE_ALT = "glyphicon glyphicon-phone-alt";
    public static final String TOWER = "glyphicon glyphicon-tower";
    public static final String STATS = "glyphicon glyphicon-stats";
    public static final String SD_VIDEO = "glyphicon glyphicon-sd-video";
    public static final String HD_VIDEO = "glyphicon glyphicon-hd-video";
    public static final String SUBTITLES = "glyphicon glyphicon-subtitles";
    public static final String SOUND_STEREO = "glyphicon glyphicon-sound-stereo";
    public static final String SOUND_DOLBY = "glyphicon glyphicon-sound-dolby";
    public static final String SOUND_5_1 = "glyphicon glyphicon-sound-5-1";
    public static final String SOUND_6_1 = "glyphicon glyphicon-sound-6-1";
    public static final String SOUND_7_1 = "glyphicon glyphicon-sound-7-1";
    public static final String COPYRIGHT_MARK = "glyphicon glyphicon-copyright-mark";
    public static final String REGISTRATION_MARK = "glyphicon glyphicon-registration-mark";
    public static final String CLOUD_DOWNLOAD = "glyphicon glyphicon-cloud-download";
    public static final String CLOUD_UPLOAD = "glyphicon glyphicon-cloud-upload";
    public static final String TREE_CONIFER = "glyphicon glyphicon-tree-conifer";
    public static final String TREE_DECIDUOUS = "glyphicon glyphicon-tree-deciduous";
    public static final String CD = "glyphicon glyphicon-cd";
    public static final String SAVE_FILE = "glyphicon glyphicon-save-file";
    public static final String OPEN_FILE = "glyphicon glyphicon-open-file";
    public static final String LEVEL_UP = "glyphicon glyphicon-level-up";
    public static final String COPY = "glyphicon glyphicon-copy";
    public static final String PASTE = "glyphicon glyphicon-paste";
    public static final String ALERT = "glyphicon glyphicon-alert";
    public static final String EQUALIZER = "glyphicon glyphicon-equalizer";
    public static final String KING = "glyphicon glyphicon-king";
    public static final String QUEEN = "glyphicon glyphicon-queen";
    public static final String PAWN = "glyphicon glyphicon-pawn";
    public static final String BISHOP = "glyphicon glyphicon-bishop";
    public static final String KNIGHT = "glyphicon glyphicon-knight";
    public static final String BABY_FORMULA = "glyphicon glyphicon-baby-formula";
    public static final String TENT = "glyphicon glyphicon-tent";
    public static final String BLACKBOARD = "glyphicon glyphicon-blackboard";
    public static final String BED = "glyphicon glyphicon-bed";
    public static final String APPLE = "glyphicon glyphicon-apple";
    public static final String ERASEGLYPHICON_HOURGLASS  = "glyphicon glyphicon-erase";
    public static final String LAMP = "glyphicon glyphicon-lamp";
    public static final String DUPLICATE = "glyphicon glyphicon-duplicate";
    public static final String PIGGY_BANK = "glyphicon glyphicon-piggy-bank";
    public static final String SCISSORS = "glyphicon glyphicon-scissors";
    public static final String BITCOIN = "glyphicon glyphicon-bitcoin";
    public static final String YEN = "glyphicon glyphicon-yen";
    public static final String RUBLE = "glyphicon glyphicon-ruble";
    public static final String SCALE = "glyphicon glyphicon-scale";
    public static final String ICE_LOLLY = "glyphicon glyphicon-ice-lolly";
    public static final String ICE_LOLLY_TASTED = "glyphicon glyphicon-ice-lolly-tasted";
    public static final String EDUCATION = "glyphicon glyphicon-education";
    public static final String OPTION_HORIZONTAL = "glyphicon glyphicon-option-horizontal";
    public static final String OPTION_VERTICAL = "glyphicon glyphicon-option-vertical";
    public static final String MENU_HAMBURGER = "glyphicon glyphicon-menu-hamburger";
    public static final String MODAL_WINDOW = "glyphicon glyphicon-modal-window";
    public static final String OIL = "glyphicon glyphicon-oil";
    public static final String GRAIN = "glyphicon glyphicon-grain";
    public static final String SUNGLASSES = "glyphicon glyphicon-sunglasses";
    public static final String TEXT_SIZE = "glyphicon glyphicon-text-size";
    public static final String TEXT_COLOR = "glyphicon glyphicon-text-color";
    public static final String TEXT_BACKGROUND = "glyphicon glyphicon-text-background";
    public static final String OBJECT_ALIGN_TOP = "glyphicon glyphicon-object-align-top";
    public static final String OBJECT_ALIGN_BOTTOM = "glyphicon glyphicon-object-align-bottom";
    public static final String OBJECT_ALIGN_HORIZONTAL = "glyphicon glyphicon-object-align-horizontal";
    public static final String OBJECT_ALIGN_LEFT = "glyphicon glyphicon-object-align-left";
    public static final String OBJECT_ALIGN_VERTICAL = "glyphicon glyphicon-object-align-vertical";
    public static final String OBJECT_ALIGN_RIGHT = "glyphicon glyphicon-object-align-right";
    public static final String TRIANGLE_RIGHT = "glyphicon glyphicon-triangle-right";
    public static final String TRIANGLE_LEFT = "glyphicon glyphicon-triangle-left";
    public static final String TRIANGLE_BOTTOM = "glyphicon glyphicon-triangle-bottom";
    public static final String TRIANGLE_TOP = "glyphicon glyphicon-triangle-top";
    public static final String CONSOLE = "glyphicon glyphicon-console";
    public static final String SUPERSCRIPT = "glyphicon glyphicon-superscript";
    public static final String SUBSCRIPT = "glyphicon glyphicon-subscript";
    public static final String MENU_LEFT = "glyphicon glyphicon-menu-left";
    public static final String MENU_RIGHT = "glyphicon glyphicon-menu-right";
    public static final String MENU_DOWN = "glyphicon glyphicon-menu-down";
    public static final String MENU_UP = "glyphicon glyphicon-menu-up";

    public static void main(String[] args) {
        Glyphicons g = new Glyphicons();
        make(g.getInput());
    }

    private static void make(String input) {
        String[] array = input.replace("\n", "").split(",");
        final String glyphicon = "glyphicon glyphicon-";
        for (String s : array) {
            String upper = s.toUpperCase().replace("-", "_");
            System.out.println("public static final String " + upper + " = \"" + glyphicon + s + "\";");
        }
    }

    private String getInput() {
        
        StringBuilder input = new StringBuilder();
        
        input.append("asterisk\n");
        input.append(",plus\n");
        input.append(",euro\n");
        input.append(",eur\n");
        input.append(",minus\n");
        input.append(",cloud\n");
        input.append(",envelope\n");
        input.append(",pencil\n");
        input.append(",glass\n");
        input.append(",music\n");
        input.append(",search\n");
        input.append(",heart\n");
        input.append(",star\n");
        input.append(",star-empty\n");
        input.append(",user\n");
        input.append(",film\n");
        input.append(",th-large\n");
        input.append(",th\n");
        input.append(",th-list\n");
        input.append(",ok\n");
        input.append(",remove\n");
        input.append(",zoom-in\n");
        input.append(",zoom-out\n");
        input.append(",off\n");
        input.append(",signal\n");
        input.append(",cog\n");
        input.append(",trash\n");
        input.append(",home\n");
        input.append(",file\n");
        input.append(",time\n");
        input.append(",road\n");
        input.append(",download-alt\n");
        input.append(",download\n");
        input.append(",upload\n");
        input.append(",inbox\n");
        input.append(",play-circle\n");
        input.append(",repeat\n");
        input.append(",refresh\n");
        input.append(",list-alt\n");
        input.append(",lock\n");
        input.append(",flag\n");
        input.append(",headphones\n");
        input.append(",volume-off\n");
        input.append(",volume-down\n");
        input.append(",volume-up\n");
        input.append(",qrcode\n");
        input.append(",barcode\n");
        input.append(",tag\n");
        input.append(",tags\n");
        input.append(",book\n");
        input.append(",bookmark\n");
        input.append(",print\n");
        input.append(",camera\n");
        input.append(",font\n");
        input.append(",bold\n");
        input.append(",italic\n");
        input.append(",text-height\n");
        input.append(",text-width\n");
        input.append(",align-left\n");
        input.append(",align-center\n");
        input.append(",align-right\n");
        input.append(",align-justify\n");
        input.append(",list\n");
        input.append(",indent-left\n");
        input.append(",indent-right\n");
        input.append(",facetime-video\n");
        input.append(",picture\n");
        input.append(",map-marker\n");
        input.append(",adjust\n");
        input.append(",tint\n");
        input.append(",edit\n");
        input.append(",share\n");
        input.append(",check\n");
        input.append(",move\n");
        input.append(",step-backward\n");
        input.append(",fast-backward\n");
        input.append(",backward\n");
        input.append(",play\n");
        input.append(",pause\n");
        input.append(",stop\n");
        input.append(",forward\n");
        input.append(",fast-forward\n");
        input.append(",step-forward\n");
        input.append(",eject\n");
        input.append(",chevron-left\n");
        input.append(",chevron-right\n");
        input.append(",plus-sign\n");
        input.append(",minus-sign\n");
        input.append(",remove-sign\n");
        input.append(",ok-sign\n");
        input.append(",question-sign\n");
        input.append(",info-sign\n");
        input.append(",screenshot\n");
        input.append(",remove-circle\n");
        input.append(",ok-circle\n");
        input.append(",ban-circle\n");
        input.append(",arrow-left\n");
        input.append(",arrow-right\n");
        input.append(",arrow-up\n");
        input.append(",arrow-down\n");
        input.append(",share-alt\n");
        input.append(",resize-full\n");
        input.append(",resize-small\n");
        input.append(",exclamation-sign\n");
        input.append(",gift\n");
        input.append(",leaf\n");
        input.append(",fire\n");
        input.append(",eye-open\n");
        input.append(",eye-close\n");
        input.append(",warning-sign\n");
        input.append(",plane\n");
        input.append(",calendar\n");
        input.append(",random\n");
        input.append(",comment\n");
        input.append(",magnet\n");
        input.append(",chevron-up\n");
        input.append(",chevron-down\n");
        input.append(",retweet\n");
        input.append(",shopping-cart\n");
        input.append(",folder-close\n");
        input.append(",folder-open\n");
        input.append(",resize-vertical\n");
        input.append(",resize-horizontal\n");
        input.append(",hdd\n");
        input.append(",bullhorn\n");
        input.append(",bell\n");
        input.append(",certificate\n");
        input.append(",thumbs-up\n");
        input.append(",thumbs-down\n");
        input.append(",hand-right\n");
        input.append(",hand-left\n");
        input.append(",hand-up\n");
        input.append(",hand-down\n");
        input.append(",circle-arrow-right\n");
        input.append(",circle-arrow-left\n");
        input.append(",circle-arrow-up\n");
        input.append(",circle-arrow-down\n");
        input.append(",globe\n");
        input.append(",wrench\n");
        input.append(",tasks\n");
        input.append(",filter\n");
        input.append(",briefcase\n");
        input.append(",fullscreen\n");
        input.append(",dashboard\n");
        input.append(",paperclip\n");
        input.append(",heart-empty\n");
        input.append(",link\n");
        input.append(",phone\n");
        input.append(",pushpin\n");
        input.append(",usd\n");
        input.append(",gbp\n");
        input.append(",sort\n");
        input.append(",sort-by-alphabet\n");
        input.append(",sort-by-alphabet-alt\n");
        input.append(",sort-by-order\n");
        input.append(",sort-by-order-alt\n");
        input.append(",sort-by-attributes\n");
        input.append(",sort-by-attributes-alt\n");
        input.append(",unchecked\n");
        input.append(",expand\n");
        input.append(",collapse-down\n");
        input.append(",collapse-up\n");
        input.append(",log-in\n");
        input.append(",flash\n");
        input.append(",log-out\n");
        input.append(",new-window\n");
        input.append(",record\n");
        input.append(",save\n");
        input.append(",open\n");
        input.append(",saved\n");
        input.append(",import\n");
        input.append(",export\n");
        input.append(",send\n");
        input.append(",floppy-disk\n");
        input.append(",floppy-saved\n");
        input.append(",floppy-remove\n");
        input.append(",floppy-save\n");
        input.append(",floppy-open\n");
        input.append(",credit-card\n");
        input.append(",transfer\n");
        input.append(",cutlery\n");
        input.append(",header\n");
        input.append(",compressed\n");
        input.append(",earphone\n");
        input.append(",phone-alt\n");
        input.append(",tower\n");
        input.append(",stats\n");
        input.append(",sd-video\n");
        input.append(",hd-video\n");
        input.append(",subtitles\n");
        input.append(",sound-stereo\n");
        input.append(",sound-dolby\n");
        input.append(",sound-5-1\n");
        input.append(",sound-6-1\n");
        input.append(",sound-7-1\n");
        input.append(",copyright-mark\n");
        input.append(",registration-mark\n");
        input.append(",cloud-download\n");
        input.append(",cloud-upload\n");
        input.append(",tree-conifer\n");
        input.append(",tree-deciduous\n");
        input.append(",cd\n");
        input.append(",save-file\n");
        input.append(",open-file\n");
        input.append(",level-up\n");
        input.append(",copy\n");
        input.append(",paste\n");
        input.append(",alert\n");
        input.append(",equalizer\n");
        input.append(",king\n");
        input.append(",queen\n");
        input.append(",pawn\n");
        input.append(",bishop\n");
        input.append(",knight\n");
        input.append(",baby-formula\n");
        input.append(",tent\n");
        input.append(",blackboard\n");
        input.append(",bed\n");
        input.append(",apple\n");
        input.append(",erase\n");
        input.append("glyphicon;hourglass\n");
        input.append(",lamp\n");
        input.append(",duplicate\n");
        input.append(",piggy-bank\n");
        input.append(",scissors\n");
        input.append(",bitcoin\n");
        input.append(",yen\n");
        input.append(",ruble\n");
        input.append(",scale\n");
        input.append(",ice-lolly\n");
        input.append(",ice-lolly-tasted\n");
        input.append(",education\n");
        input.append(",option-horizontal\n");
        input.append(",option-vertical\n");
        input.append(",menu-hamburger\n");
        input.append(",modal-window\n");
        input.append(",oil\n");
        input.append(",grain\n");
        input.append(",sunglasses\n");
        input.append(",text-size\n");
        input.append(",text-color\n");
        input.append(",text-background\n");
        input.append(",object-align-top\n");
        input.append(",object-align-bottom\n");
        input.append(",object-align-horizontal\n");
        input.append(",object-align-left\n");
        input.append(",object-align-vertical\n");
        input.append(",object-align-right\n");
        input.append(",triangle-right\n");
        input.append(",triangle-left\n");
        input.append(",triangle-bottom\n");
        input.append(",triangle-top\n");
        input.append(",console\n");
        input.append(",superscript\n");
        input.append(",subscript\n");
        input.append(",menu-left\n");
        input.append(",menu-right\n");
        input.append(",menu-down\n");
        input.append(",menu-up");

        return input.toString();
    }
}
