/**
 * ﻿Copyright 2014-2018 Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Copyright 2009 - 2016
 *
 * Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Fraunhofer IWES
 *
 * All Rights reserved
 */
/**
 * Copyright 2009 - 2014
 *
 * Fraunhofer-Gesellschaft zur Förderung der angewandten Wissenschaften e.V.
 *
 * Fraunhofer IIS Fraunhofer ISE Fraunhofer IWES
 *
 * All Rights reserved
 */
package de.iwes.sim.roominside.hmmotionsensor;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.ogema.apps.roomsim.service.api.RoomSimulationService;
import org.ogema.apps.roomsim.service.api.helpers.RoomConnection;
import org.ogema.apps.roomsim.service.api.helpers.RoomInsideLogicBase;
import org.ogema.apps.roomsim.service.api.helpers.RoomInsideSimBase;
import org.ogema.core.application.ApplicationManager;
import org.ogema.core.application.Timer;
import org.ogema.core.model.Resource;
import org.ogema.model.devices.sensoractordevices.SensorDevice;
import org.ogema.tools.simulation.service.api.model.SimulatedQuantity;
import org.ogema.tools.simulation.service.api.model.SimulationConfiguration;

import de.iwes.util.resource.ValueResourceHelper;

/**
 * A simulation provider, that simulates e.g. a particular sort of devices. 
 * In this example, a the power generated by a PV plant is simulated.  
 */
public class HMMotionSensorSimulation extends RoomInsideSimBase<HMMotionSensorConfigPattern, HMMotionSensorPattern> {
	
	private static final long SIM_UPDATE_INTERVAL = 4000;
	@Override
	protected long getDefaultUpdateInterval(){return SIM_UPDATE_INTERVAL;}

	// callbacks are guaranteed to come in the same thread, no need to synchronize on the map
	private final Map<String,SimulatedMotionSens> simulatedObjects = new HashMap<>();
	private final RoomSimulationService roomSimService;
	
	public HMMotionSensorSimulation(ApplicationManager am, RoomSimulationService roomSimService) {
		super(am, HMMotionSensorPattern.class, false, HMMotionSensorConfigPattern.class);
		this.roomSimService = roomSimService;
	}	

	@Override
	public String getProviderId() {
		return "HM Motion Sensor simulation _Room Simulation_";
	}
	
	@Override
	public Class<? extends Resource> getSimulatedType() {
		return SensorDevice.class;
	}

	@Override
	public void buildConfigurations(HMMotionSensorPattern pattern, List<SimulationConfiguration> cfgs, HMMotionSensorConfigPattern simPattern) {
		// Add here configuration values that can be edited by the user, see example below
		cfgs.add(new RoomConnection<>(simPattern.roomSimulationToConnect, appManager.getResourceAccess(),
				roomSimService, this, simPattern));
	}
	
	@Override
	public void buildQuantities(HMMotionSensorPattern pattern, List<SimulatedQuantity> quantities, HMMotionSensorConfigPattern simPattern) {
		// Add here configuration values that can be edited by the user, see example below
	}
	
	@Override
	public String getDescription() {
		return "Simulated motion/brightness sensor connected into room via Room Simulation Service."
				+ " Note that after creation of a simulated object the room connector has to be set before"
				+ "the simulation can be activated.";
	}
	
	@Override
	public void simTimerElapsed(HMMotionSensorPattern targetPattern, HMMotionSensorConfigPattern configPattern, Timer t, long timeStep) {
		//here the timing is provided by the room simulations service directly to the component
	}

	
	@SuppressWarnings("unchecked")
	@Override
	protected void initSimulation(HMMotionSensorPattern targetPattern, HMMotionSensorConfigPattern configPattern) {
		// initialize and activate also the optional fields in targetPattern
		boolean finalActivate = false;
		if(ValueResourceHelper.setIfNew(targetPattern.motion, false) |
				ValueResourceHelper.setIfNew(targetPattern.brightness, 0.1f) |
				ValueResourceHelper.setIfNew(targetPattern.batteryVoltage, 2.6f) |
				ValueResourceHelper.setIfNew(targetPattern.elStorageType, 1) |
				ValueResourceHelper.setIfNew(targetPattern.batteryStatus, 0.8f)) {
			finalActivate = true;
		}
		if(finalActivate) {
			targetPattern.model.activate(true);
		}

		SimulatedMotionSens logic = new SimulatedMotionSens(appManager, targetPattern, configPattern,
				roomSimService, this);
		simulatedObjects.put(targetPattern.model.getLocation(), logic);
	}
	
	@Override
	protected void removeSimulation(HMMotionSensorPattern targetPattern, HMMotionSensorConfigPattern configPattern) {
		SimulatedMotionSens logic = simulatedObjects.remove(targetPattern.model.getLocation());
		logic.close();
	}

	@Override
	protected RoomInsideLogicBase<?> getSimulatedObjects(String simLocation) {
		return simulatedObjects.get(simLocation);
	}
}
